# Generated by Django 4.0.6 on 2022-08-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpe', '0002_story_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystory',
            name='content',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='mystory',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
