# Generated by Django 4.0.6 on 2022-08-05 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petpe', '0003_alter_mystory_content_alter_mystory_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-createdAt']},
        ),
    ]
