# Generated by Django 4.0.6 on 2022-08-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petpe', '0005_storycomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyStory',
        ),
    ]
