# Generated by Django 4.0.6 on 2022-08-16 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petpe', '0006_delete_mystory'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image_likes',
            field=models.ManyToManyField(blank=True, related_name='like_stories', to=settings.AUTH_USER_MODEL),
        ),
    ]
