# Generated by Django 4.0.6 on 2022-08-16 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petpe', '0008_alter_story_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stroypicture',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storypicture', to='petpe.story'),
        ),
    ]
