# Generated by Django 4.0.6 on 2022-08-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userimage',
            field=models.ImageField(default='default.jpg', null=True, upload_to='userimages/'),
        ),
    ]
