# Generated by Django 4.0.6 on 2022-08-16 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Socialring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('workout', 'workout'), ('food', 'food'), ('travel', 'travel'), ('education', 'education'), ('growth', 'growth')], max_length=50, null=True)),
                ('type', models.CharField(blank=True, choices=[('online', 'online'), ('offline', 'offline')], max_length=50, null=True)),
                ('meetdate', models.DateField(null=True)),
                ('meettime', models.TimeField(null=True)),
                ('maxpeople', models.IntegerField(null=True)),
                ('count', models.IntegerField(blank=True, default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('flag', models.CharField(blank=True, max_length=50, null=True)),
                ('user_jud', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialringComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('socialring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.socialring')),
            ],
        ),
        migrations.CreateModel(
            name='joinlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True, unique=True)),
                ('num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.socialring')),
            ],
        ),
    ]
