# Generated by Django 4.0.6 on 2022-08-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_socialring_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialringcomment',
            name='comment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
