# Generated by Django 4.0.6 on 2022-08-17 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_socialringcomment_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialringcomment',
            name='socialring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialringcomment', to='social.socialring'),
        ),
    ]
