# Generated by Django 4.0.6 on 2022-08-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_socialringcomment_socialring'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialring',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='socialring',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
